# Generated by Django 4.1.7 on 2023-04-17 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctortable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctortable', models.CharField(max_length=200)),
                ('docspec', models.CharField(max_length=500)),
                ('doctimage', models.ImageField(upload_to='main')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projapp1.department')),
            ],
        ),
    ]
